name = "ContinuumArrays"
uuid = "7ae1f121-cc2c-504b-ac30-9b923412ae5c"
version = "0.17.3"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
Infinities = "e1ba4f0e-776d-440f-acd9-e1d2e9742647"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuasiArrays = "c4ea9172-b204-11e9-377d-29865faadc5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extensions]
ContinuumArraysMakieExt = "Makie"
ContinuumArraysRecipesBaseExt = "RecipesBase"

[compat]
AbstractFFTs = "1.0"
ArrayLayouts = "1.0"
BandedMatrices = "0.17, 1"
BlockArrays = "0.16"
DomainSets = "0.6, 0.7"
FastTransforms = "0.15, 0.16"
FillArrays = "1.0"
InfiniteArrays = "0.12, 0.13"
Infinities = "0.1"
IntervalSets = "0.7"
LazyArrays = "1.7"
Makie = "0.19, 0.20"
QuasiArrays = "0.11.1"
RecipesBase = "1.0"
StaticArrays = "1.0"
julia = "1.9"

[extras]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Base64", "FastTransforms", "RecipesBase", "Makie", "Test"]
