name = "ContinuumArrays"
uuid = "7ae1f121-cc2c-504b-ac30-9b923412ae5c"
version = "0.2.1"

[deps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuasiArrays = "c4ea9172-b204-11e9-377d-29865faadc5c"

[compat]
ArrayLayouts = "0.1"
BandedMatrices = "0.14.2"
FillArrays = "0.8.2"
IntervalSets = "0.3.2, 0.4"
LazyArrays = "0.14.11, 0.15, 0.16"
QuasiArrays = "0.1.1, 0.2"
julia = "1.3"

[extras]
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FastTransforms", "Test"]
